docker_containers_catalog:
  npm:
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - '{{ docker_bind_catalog.config.mnt }}/npm/data:/data'
      - '{{ docker_bind_catalog.config.mnt }}/npm/letsencrypt:/etc/letsencrypt'

  termix:
    image: "ghcr.io/lukegus/termix:latest"
    ports:
      - "8443:8443"
    volumes:
      - '{{ docker_bind_catalog.config.mnt }}/termix:/app/data'
    env:
      PUID: "1000"
      PGID: "1000"
      ENABLE_SSL: "true"
      SSL_KEY_PATH: "/app/data/ssl/termix.key"
      SSL_CERT_PATH: "/app/data/ssl/termix.crt"
      SSL_PORT: "8443"

  nextcloud:
    image: "lscr.io/linuxserver/nextcloud:latest"
    ports:
      - "8097:8097"
    volumes:
      - '{{ docker_bind_catalog.config.mnt }}/nextcloud:/config'
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "america/detroit"

  jellyfin:
    image: "jellyfin/jellyfin:latest"
    ports:
      - "8096:8096"
    volumes:
      - '{{ docker_bind_catalog.config.mnt }}/jellyfin/config:/config'
      - '{{ docker_bind_catalog.nott.mnt }}:/cache'
      - '{{ docker_bind_catalog.media.mnt }}:/media'
    devices:
      - "/dev/dri:/dev/dri"

  ombi:
    image: "linuxserver/ombi:latest"
    ports:
      - "3579:3579"
    volumes:
      - '{{ docker_bind_catalog.config.mnt }}/ombi:/config'
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "america/detroit"

  prowlarr:
    image: "linuxserver/prowlarr:latest"
    ports:
      - "9696:9696"
    volumes:
      - '{{ docker_bind_catalog.config.mnt }}/prowlarr:/config'
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "america/detroit"

  sonarr:
    image: "linuxserver/sonarr:latest"
    ports:
      - "8989:8989"
    volumes:
      - '{{ docker_bind_catalog.config.mnt }}/sonarr:/config'
      - '{{ docker_bind_catalog.media.mnt }}/tv:/tv'
      - '{{ docker_bind_catalog.media.mnt }}/downloads:/downloads'
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "america/detroit"

  radarr:
    image: "linuxserver/radarr:latest"
    ports:
      - "7878:7878"
    volumes:
      - '{{ docker_bind_catalog.config.mnt  }}/radarr:/config'
      - '{{ docker_bind_catalog.media.mnt }}/movies:/movies'
      - '{{ docker_bind_catalog.media.mnt }}/downloads:/downloads'
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "america/detroit"

  lidarr:
    image: "linuxserver/lidarr:latest"
    ports:
      - "8686:8686"
    volumes:
      - '{{ docker_bind_catalog.config.mnt  }}/lidarr:/config'
      - '{{ docker_bind_catalog.media.mnt }}/music:/music'
      - '{{ docker_bind_catalog.media.mnt }}/downloads:/downloads'
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "america/detroit"

  qbittorrent:
    image: "linuxserver/qbittorrent:latest"
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    volumes:
      - '{{ docker_bind_catalog.config.mnt  }}/qbittorrent:/config'
      - '{{ docker_bind_catalog.media.mnt  }}/downloads:/downloads'
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "america/detroit"
      WEBGUI_PORT: "8080"
      TORRENTING_PORT: "6881"


  immich_server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ports:
      - 2283:2283
    volumes:
      - '{{ docker_bind_catalog.media.mnt }}/images:/data'
      - /etc/localtime:/etc/localtime:ro
    restart_policy: always
  immich_machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - '{{ docker_bind_catalog.nott.mnt }}/immich/cache:/cache'
    restart_policy: always
  immich_redis:
    image: docker.io/valkey/valkey:9@sha256:3b55fbaa0cd93cf0d9d961f405e4dfcc70efe325e2d84da207a0a8e6d8fde4f9
    restart_policy: always
  immich_postgres:
    image: 
      ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    volumes:
      - '{{ docker_bind_catalog.config.mnt }}/immich/postgres:/var/lib/postgresql/data'
    env:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    restart_policy: always
docker_groups_catalog:
  piracy:
    radarr:
    lidarr:
    sonarr:
    prowlarr:
    qbittorrent:

  proxys:
    npm:

  public:
    jellyfin:
    npm:
    ombi:
    termix:
    nextcloud:

  testing:
    radarr:
    sonarr:
    termix:
