users_catalog:
  robot:
    pub_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID5Pv9apJOGqYOWb7iYsJhH6u5s54NF1dlXf41ZiIByU
    pri_key: ../secrets/id_robot
  casey:
    pub_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAJgJvj90uIj+Q2Xb45FkRZbNScp9RcX6QsU2GqXyOeU
  robot_init:
    pub_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHQYKkTYcGnQDB7PxLuMp525rr84n7U5vROuJBDDot1/
    pri_key: ../secrets/id_robot_init

key_store:
  pve_api:
    key: "{{ vault_pve_api_key }}"
    id: robot_token

ansible_private_key_file: '{{ users_catalog.robot.pri_key }}'
