robot_key: "{{ lookup('file','~/secrets/robot.pub') }}"
robot_id: ~/.ssh/id_robot

casey_key: "{{ lookup('file','~/secrets/casey.pub') }}"

robot_init_key: "{{ lookup('file','~/secrets/robot_init.pub') }}"
robot_init_id: ~/.ssh/id_robot_init')

pve_api_key: "{{ lookup('file','~/secrets/pve_api_key') }}"

ansible_private_key_file: '{{ robot_id }}'
