users_catalog:  # pick many
  robot:
    key: "{{ lookup('file','~/secrets/robot.pub') }}"
    id: ~/.ssh/id_robot
  casey:
    key: "{{ lookup('file','~/secrets/casey.pub') }}"
  robot_init:
    key: "{{ lookup('file','~/secrets/robot_init.pub') }}"
    id: ~/.ssh/id_robot_init

api_catalog:  # reference
  pve_api:
    key: "{{ lookup('file','~/secrets/pve_api_key') }}"
    id: robot_token

ansible_private_key_file: '{{ users_catalog.robot.id }}'
