---
# tasks file for pve_dl_ct
- name: DEBUG Var
  debug:
    var: platform

- name: Build Proxmox Containers
  include_tasks: pct.yml
  when: platform == 'pct'

- name: Build VMs
  include_tasks: qemu.yml
  when: platform == 'qemu'

- name: No platform to build.
  debug:
    msg: "Skipping Virtual Platform Deployment"
  when: platform not in ["pct", "qemu"]
