galaxy_info:
  author: frankenas
  description: Register a pinned (static-anchor) host's DNS record on the central dnsmasq server
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags: []

dependencies: []
