galaxy_info:
  author: frankenas
  description: Central authentication / SSO server config (Authelia + Redis, file backend + TOTP)
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags: []

dependencies: []
