ansible_host: test-port-02
users_enabled:
  casey:
  robot:
compute_enabled: small
network_enabled:
  oob:
  wan:
os_enabled: ubuntu
storage_enabled: s8
dns_enabled: oob
ovpn_server_enabled: ca_toronto
