- name: Provision
  hosts: test-port-01
  gather_facts: false
  connection: local
  roles:
    - pve_dl_ct

- name: Configure
  hosts: test-port-01
  gather_facts: true
  roles:
    - dl_base
    - docker
