
#Fully provisions hosts who are docker hosts.
- name: Provision docker hosts
  hosts: docker
  gather_facts: false
  connection: local
  roles:
    - role: pve_dl
      when: "'droplets' in group_names"

- name: Configure docker hosts
  hosts: docker
  gather_facts: true
  roles:
    - docker
