#Fully provisions hosts who are docker hosts.
- name: Provision docker hosts
  hosts: docker
  gather_facts: false
  connection: local
  roles:
    - pve_dl

- name: Configure docker hosts
  hosts: docker
  gather_facts: true
  roles:
    - dl_base
    - docker
