galaxy_info:
  author: frankenas
  description: Provision Proxmox guests (LXC/QEMU) with networks, mounts, and hypervisor firewall
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags: []

dependencies: []
